// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sophon.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct AssetChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var chunkName: String = String()

  var chunkDecompressedHashMd5: String = String()

  var chunkOnFileOffset: Int64 = 0

  var chunkSize: Int64 = 0

  var chunkSizeDecompressed: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct AssetProperty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var assetName: String = String()

  var assetChunks: [AssetChunk] = []

  var assetType: Int32 = 0

  var assetSize: Int64 = 0

  var assetHashMd5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonManifest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var assets: [AssetProperty] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct PatchInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var patchFileSize: Int64 = 0

  var patchStartOffset: Int64 = 0

  var patchLength: Int64 = 0

  var originalFileName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct PatchesEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: String = String()

  var patchInfo: PatchInfo {
    get {_patchInfo ?? PatchInfo()}
    set {_patchInfo = newValue}
  }
  /// Returns true if `patchInfo` has been explicitly set.
  var hasPatchInfo: Bool {self._patchInfo != nil}
  /// Clears the value of `patchInfo`. Subsequent reads from it will return its default value.
  mutating func clearPatchInfo() {self._patchInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _patchInfo: PatchInfo? = nil
}

nonisolated struct PatchFileData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileName: String = String()

  var fileSize: Int64 = 0

  var fileHash: String = String()

  var patchesEntries: [PatchesEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct FileInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct DeleteFiles: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var infos: [FileInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct DeleteFilesEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: String = String()

  var deleteFiles: DeleteFiles {
    get {_deleteFiles ?? DeleteFiles()}
    set {_deleteFiles = newValue}
  }
  /// Returns true if `deleteFiles` has been explicitly set.
  var hasDeleteFiles: Bool {self._deleteFiles != nil}
  /// Clears the value of `deleteFiles`. Subsequent reads from it will return its default value.
  mutating func clearDeleteFiles() {self._deleteFiles = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _deleteFiles: DeleteFiles? = nil
}

nonisolated struct PatchManifest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileDatas: [PatchFileData] = []

  var deleteFilesEntries: [DeleteFilesEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension AssetChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AssetChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chunk_name\0\u{3}chunk_decompressed_hash_md5\0\u{3}chunk_on_file_offset\0\u{3}chunk_size\0\u{3}chunk_size_decompressed\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.chunkName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.chunkDecompressedHashMd5) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.chunkOnFileOffset) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.chunkSize) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.chunkSizeDecompressed) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chunkName.isEmpty {
      try visitor.visitSingularStringField(value: self.chunkName, fieldNumber: 1)
    }
    if !self.chunkDecompressedHashMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.chunkDecompressedHashMd5, fieldNumber: 2)
    }
    if self.chunkOnFileOffset != 0 {
      try visitor.visitSingularInt64Field(value: self.chunkOnFileOffset, fieldNumber: 3)
    }
    if self.chunkSize != 0 {
      try visitor.visitSingularInt64Field(value: self.chunkSize, fieldNumber: 4)
    }
    if self.chunkSizeDecompressed != 0 {
      try visitor.visitSingularInt64Field(value: self.chunkSizeDecompressed, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AssetChunk, rhs: AssetChunk) -> Bool {
    if lhs.chunkName != rhs.chunkName {return false}
    if lhs.chunkDecompressedHashMd5 != rhs.chunkDecompressedHashMd5 {return false}
    if lhs.chunkOnFileOffset != rhs.chunkOnFileOffset {return false}
    if lhs.chunkSize != rhs.chunkSize {return false}
    if lhs.chunkSizeDecompressed != rhs.chunkSizeDecompressed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension AssetProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AssetProperty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}asset_name\0\u{3}asset_chunks\0\u{3}asset_type\0\u{3}asset_size\0\u{3}asset_hash_md5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.assetName) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.assetChunks) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.assetType) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.assetSize) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.assetHashMd5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.assetName.isEmpty {
      try visitor.visitSingularStringField(value: self.assetName, fieldNumber: 1)
    }
    if !self.assetChunks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assetChunks, fieldNumber: 2)
    }
    if self.assetType != 0 {
      try visitor.visitSingularInt32Field(value: self.assetType, fieldNumber: 3)
    }
    if self.assetSize != 0 {
      try visitor.visitSingularInt64Field(value: self.assetSize, fieldNumber: 4)
    }
    if !self.assetHashMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.assetHashMd5, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AssetProperty, rhs: AssetProperty) -> Bool {
    if lhs.assetName != rhs.assetName {return false}
    if lhs.assetChunks != rhs.assetChunks {return false}
    if lhs.assetType != rhs.assetType {return false}
    if lhs.assetSize != rhs.assetSize {return false}
    if lhs.assetHashMd5 != rhs.assetHashMd5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonManifest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonManifest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}assets\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.assets) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.assets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assets, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonManifest, rhs: SophonManifest) -> Bool {
    if lhs.assets != rhs.assets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PatchInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PatchInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{4}\u{3}patch_file_size\0\u{4}\u{2}patch_start_offset\0\u{3}patch_length\0\u{3}original_file_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.patchFileSize) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.patchStartOffset) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.patchLength) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.originalFileName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.patchFileSize != 0 {
      try visitor.visitSingularInt64Field(value: self.patchFileSize, fieldNumber: 4)
    }
    if self.patchStartOffset != 0 {
      try visitor.visitSingularInt64Field(value: self.patchStartOffset, fieldNumber: 6)
    }
    if self.patchLength != 0 {
      try visitor.visitSingularInt64Field(value: self.patchLength, fieldNumber: 7)
    }
    if !self.originalFileName.isEmpty {
      try visitor.visitSingularStringField(value: self.originalFileName, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PatchInfo, rhs: PatchInfo) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.patchFileSize != rhs.patchFileSize {return false}
    if lhs.patchStartOffset != rhs.patchStartOffset {return false}
    if lhs.patchLength != rhs.patchLength {return false}
    if lhs.originalFileName != rhs.originalFileName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PatchesEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PatchesEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}patch_info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._patchInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    try { if let v = self._patchInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PatchesEntry, rhs: PatchesEntry) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs._patchInfo != rhs._patchInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PatchFileData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PatchFileData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_name\0\u{3}file_size\0\u{3}file_hash\0\u{3}patches_entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileName) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.fileSize) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fileHash) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.patchesEntries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileName.isEmpty {
      try visitor.visitSingularStringField(value: self.fileName, fieldNumber: 1)
    }
    if self.fileSize != 0 {
      try visitor.visitSingularInt64Field(value: self.fileSize, fieldNumber: 2)
    }
    if !self.fileHash.isEmpty {
      try visitor.visitSingularStringField(value: self.fileHash, fieldNumber: 3)
    }
    if !self.patchesEntries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.patchesEntries, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PatchFileData, rhs: PatchFileData) -> Bool {
    if lhs.fileName != rhs.fileName {return false}
    if lhs.fileSize != rhs.fileSize {return false}
    if lhs.fileHash != rhs.fileHash {return false}
    if lhs.patchesEntries != rhs.patchesEntries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension FileInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FileInfo, rhs: FileInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DeleteFiles: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "DeleteFiles"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}infos\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.infos) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.infos.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.infos, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DeleteFiles, rhs: DeleteFiles) -> Bool {
    if lhs.infos != rhs.infos {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DeleteFilesEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "DeleteFilesEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}delete_files\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._deleteFiles) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    try { if let v = self._deleteFiles {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DeleteFilesEntry, rhs: DeleteFilesEntry) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs._deleteFiles != rhs._deleteFiles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PatchManifest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PatchManifest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_datas\0\u{3}delete_files_entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.fileDatas) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.deleteFilesEntries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileDatas.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fileDatas, fieldNumber: 1)
    }
    if !self.deleteFilesEntries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.deleteFilesEntries, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PatchManifest, rhs: PatchManifest) -> Bool {
    if lhs.fileDatas != rhs.fileDatas {return false}
    if lhs.deleteFilesEntries != rhs.deleteFilesEntries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
