import { defineConfig } from "tsup";

const bundledDependencies = [
  "abort-controller",
  "async-lock",
  "available-typed-arrays",
  "base64-js",
  "buffer",
  "call-bind",
  "call-bind-apply-helpers",
  "call-bound",
  "clean-git-ref",
  "crc-32",
  "decompress-response",
  "define-data-property",
  "diff3",
  "dunder-proto",
  "es-define-property",
  "es-errors",
  "es-object-atoms",
  "event-target-shim",
  "events",
  "for-each",
  "function-bind",
  "get-intrinsic",
  "get-proto",
  "gopd",
  "has-property-descriptors",
  "has-symbols",
  "has-tostringtag",
  "hasown",
  "ieee754",
  "ignore",
  "inherits",
  "is-callable",
  "is-typed-array",
  "isarray",
  "isomorphic-git",
  "math-intrinsics",
  "mimic-response",
  "minimist",
  "minimisted",
  "once",
  "pako",
  "pify",
  "possible-typed-array-names",
  "process",
  "readable-stream",
  "safe-buffer",
  "set-function-length",
  "sha.js",
  "simple-concat",
  "simple-get",
  "string_decoder",
  "to-buffer",
  "typed-array-buffer",
  "which-typed-array",
  "wrappy",
];

export default defineConfig({
  entry: ["server.ts"],
  format: ["esm"],
  outDir: "build",
  banner: {
    js: 'import { createRequire } from "node:module"; var require = createRequire(import.meta.url);',
  },
  external: ["better-sqlite3", "next"],
  noExternal: bundledDependencies,
});
